version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    restart: unless-stopped
    depends_on:
      - backend-go
      - backend-py
      - elasticsearch
    ports:
      - 3001:3001
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - parcel_cache:/app/.parcel-cache
      - yarn_cache:/usr/local/share/.cache/yarn/v6
    command: ["yarn", "start"]
  backend-go:
    build:
      context: ./backend/go
    container_name: backend-go
    restart: unless-stopped
    depends_on:
      - elasticsearch
    ports:
      - 3000:3000
    volumes:
      - ./backend/go:/app
    command: ["air"]
  backend-py:
    build:
      context: ./backend/python
    container_name: backend-py
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - ./backend/python:/app
    command: ["./docker-entrypoint.sh"]
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    container_name: elasticsearch
    restart: unless-stopped
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data
  es-admin:
    image: stephanediondev/elasticsearch-admin
    container_name: es-admin
    restart: unless-stopped
    depends_on:
      - elasticsearch
    ports:
      - 8080:8080
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - SECRET_REGISTER=goes

volumes:
  esdata:
  parcel_cache:
  yarn_cache:
